<a href="https://colab.research.google.com/github/hetmangukiya32/Data-Science-and-Machine-Learning/blob/main/01-Python/Pandas/advance/Advance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas 2 **bold text**

In [1]:
import pandas as pd

student = {
    "Name": ["Het", "Rahul", "Amit"],
    "Age": [21, 22, 20],
    "City": ["Surat", "Ahmedabad", "Rajkot"]
}

df = pd.DataFrame(student)

print(df)
# loc = Label → (row label, column name)
# iloc = Integer Location → (row position, column position)

# Row Label (Index) = 0, 1, 2 (or custom labels like S1, S2, S3)
# Column Name = Name, Age, City

    Name  Age       City
0    Het   21      Surat
1  Rahul   22  Ahmedabad
2   Amit   20     Rajkot

In [15]:
df.loc[0:3]

        City
0      Surat
1  Ahmedabad
2      Surat
3     Rajkot

In [13]:
# What does iloc use?
# iloc doesn't use names.
# It uses positions.
print(df.iloc[1, 0])

Ahmedabad

In [5]:
import pandas as pd

student = {
    "Name": ["Het", "Rahul", "Amit"],
    "Age": [21, 22, 20],
    "City": ["Surat", "Ahmedabad", "Rajkot"],
    "Marks": [90, 80, 85]
}

df = pd.DataFrame(student)

print(df)
print(df["Age"])
print(df["Marks"])
print(df[["Name", "Age"]])
print(type(df["Name"]))
print(df["Age"] > 20)
print(df["City"] == "Surat")      #Creates True/False values
# Now Filter
print(df[df["City"] == "Surat"])   #return only matching rows

    Name  Age       City  Marks
0    Het   21      Surat     90
1  Rahul   22  Ahmedabad     80
2   Amit   20     Rajkot     85
0    21
1    22
2    20
Name: Age, dtype: int64
0    90
1    80
2    85
Name: Marks, dtype: int64
    Name  Age
0    Het   21
1  Rahul   22
2   Amit   20
<class 'pandas.core.series.Series'>
0     True
1     True
2    False
Name: Age, dtype: bool
0     True
1    False
2    False
Name: City, dtype: bool
  Name  Age   City  Marks
0  Het   21  Surat     90

In [9]:
# What is nunique()?
# nunique() means:
# Number of Unique Values
# It counts how many different (unique) values are present in a column.
import pandas as pd

data = {
    "City": ["Surat", "Ahmedabad", "Surat", "Rajkot", "Rajkot"]
}

df = pd.DataFrame(data)

# print(df)
print(df["City"].nunique())
print(df["City"].unique())

3
['Surat' 'Ahmedabad' 'Rajkot']

In [16]:
import pandas as pd

data = {
    "Name": ["Het", "Rahul", "Amit", "Neha"],
    "Age": [21, None, 20, 23],
    "City": ["Surat", "Ahmedabad", None, "Vadodara"]
}

df = pd.DataFrame(data)

# Save as CSV
df.to_csv("raw_data.csv", index=False)

print(df)
#True in place of null

    Name   Age       City
0    Het  21.0      Surat
1  Rahul   NaN  Ahmedabad
2   Amit  20.0       None
3   Neha  23.0   Vadodara

In [17]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [20]:
df.isnull().sum()
#Null row drop

Name    0
Age     1
City    1
dtype: int64

In [19]:
df.dropna()

   Name   Age      City
0   Het  21.0     Surat
3  Neha  23.0  Vadodara

In [21]:
# dropna(axis=1)
df.dropna(axis=1)
##remove column

    Name
0    Het
1  Rahul
2   Amit
3   Neha

In [22]:
# fillna(0)
df.fillna(0)

    Name   Age       City
0    Het  21.0      Surat
1  Rahul   0.0  Ahmedabad
2   Amit  20.0          0
3   Neha  23.0   Vadodara

In [24]:
# Fill Age with Mean
# df["Age"] = df["Age"].fillna(df["Age"].mean())

In [25]:
# ffill()
# uper ansewr give down row
# Forward Fill
df.ffill()

    Name        Age       City
0    Het  21.000000      Surat
1  Rahul  21.333333  Ahmedabad
2   Amit  20.000000  Ahmedabad
3   Neha  23.000000   Vadodara

In [26]:
# bfill()
# Backward Fill

df.bfill()

    Name        Age       City
0    Het  21.000000      Surat
1  Rahul  21.333333  Ahmedabad
2   Amit  20.000000   Vadodara
3   Neha  23.000000   Vadodara